spring:
  datasource:
    url: jdbc:h2:mem:test;
    username: sa
    password:
    driverClassName: org.h2.Driver


  jpa:
    show-sql: true


    hibernate:
      ddl-auto: update
      javax:
        cache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: jcache
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8081